### ISSUE TITLE
Database exception if db wasn't created yet

### ISSUE THREAD

**Issue by fernandomm** [barsoom/traco#34]
This is similar to #30.

If you use locale_columns in a validates call, it will raise an exception if the database wasn't created yet. This happens when running rake db:create or other similar tasks. Example:

```
validates *locale_columns(:name), presence: true
```

The exception looks like this:

```
Mysql2::Error: Table 'test.templates' doesn't exist
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:324:in `execute_and_free'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:471:in `columns'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/attributes.rb:93:in `columns'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/attributes.rb:98:in `columns_hash'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:205:in `subclass_from_attributes?'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:54:in `new'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/traco-3.2.1/lib/traco/class_methods.rb:66:in `traco_cache'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/traco-3.2.1/lib/traco/class_methods.rb:15:in `_locale_columns_for_attribute'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/traco-3.2.1/lib/traco/class_methods.rb:9:in `block in locale_columns'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/traco-3.2.1/lib/traco/class_methods.rb:8:in `each'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/traco-3.2.1/lib/traco/class_methods.rb:8:in `each_with_object'
/Users/fernando/.rvm/gems/ruby-2.3.5/gems/traco-3.2.1/lib/traco/class_methods.rb:8:in `locale_columns'
```

**Comment by henrik** [comment]
Oops, didn't see this issue until now. Sorry about that.

I wonder if this is specific to the Mysql2 engine or if I haven't seen it myself for other reasons.

Want to make a PR? :)

**Comment by henrik** [comment]
I'm going to close this, as I know I won't get around to this, but if @fernandomm or someone else wants to make a PR, please feel free :)
